### PR TITLE
Database Orders: Allow for adding custom columns

### LINKED ISSUE #634: Blueprint fields missing in order view after database migration
### What's the issue you're running into?

In version V2.* we added a number of fields to the order blueprint like radio_dhl_servicepoint, dhl_servicepoint_name and optional_donation. After the update to V3.0.* and migration to the database these fields are available, as JSON, in the orders table in a column called data. But we are not able to view these fields anymore in the Order (now Runway) view.

Can you point me in the right direction (e.g. documentation / video or...) where I can see more about how to configure this so that in CP these custom (Blueprint) fields, like DHL servicepoint, are shown?

### Steps to reproduce

1. Create custom fields in the order blueprint (V2.*)
2. Upgrade to V3.0.*
3. Migrate to the database
4. View (missing) fields in the CP Runway Order view

### Environment

Statamic 3.3.12 Pro
Laravel 8.83.13
PHP 8.0.19
doublethreedigital/runway 2.3.5
doublethreedigital/simple-commerce 3.0.4
joetannenbaum/antlers-stack-tags 0.1.0
optimoapps/statamic-bard-text-align 1.0.2
roorda-ict/statamic-entries-export 1.0.0

### PR DESCRIPTION
**Pull request by duncanmcclean**
This pull request adds support for developers adding custom columns to the `orders`/`customers` tables. 

**For example:** a store may wish to store data about a pickup point but they probably don't want that data to live inside a JSON column (like it would currently)

This also means developers can edit these columns inside Runway which they wouldn't be able to do if the data was stored inside the `data` column.

Closes #634

## Note for existing database users

If you've already setup a database prior to this change, you'll need to install the `doctrine/dbal` dependency. You can do this by running the following command:

```
composer require doctrine/dbal
```

## To Do

* [X] Orders: Reading from custom columns
* [X] Orders: Writing back to custom columns
* [X] Orders: Write tests for both read/write
* [x] Customers: Reading from custom columns
* [x] Customers: Writing back to custom columns
* [x] Customers: Write tests for both read/write
* [x] Update documentation to mention 'custom column' functionality

### CODE REVIEW

File: src/Orders/OrderModel.php [hunk 1]
```diff
@@ -36,6 +29,9 @@ class OrderModel extends Model
         'gateway' => 'json',
         'data' => 'json',
         'paid_date' => 'datetime',
+
+        // Ignore this. Needed for SC's test suite.
+        'ordered_on_tuesday' => 'boolean',
```
Comment (duncanmcclean) [inline src/Orders/OrderModel.php]: We can probably change this `ordered_on_tuesday` to not have a casted value, then we won't need it here.
